-- Vocabulary gloss/pinyin cleanup, 2026-08-28
-- Generated by content/vocab_fixes_20260828.py
-- Backup taken first: backups/vocabulary_backup_20260828_114759.json

UPDATE vocabulary SET meaning = 'child; adds an "r" sound to the end of a word' WHERE word = '儿' AND pinyin = 'ér';
UPDATE vocabulary SET meaning = 'a person who does something' WHERE word = '者';
UPDATE vocabulary SET meaning = 'some (only after "one", "this" or "that")' WHERE word = '些';
UPDATE vocabulary SET meaning = 'two (when counting things)' WHERE word = '两';
UPDATE vocabulary SET meaning = 'two (the number itself)' WHERE word = '二';
UPDATE vocabulary SET meaning = 'the all-purpose counting word' WHERE word = '个';
UPDATE vocabulary SET meaning = 'counting word for books' WHERE word = '本';
UPDATE vocabulary SET meaning = 'mouth; counting word for family members' WHERE word = '口';
UPDATE vocabulary SET meaning = 'son' WHERE word = '儿子';
UPDATE vocabulary SET meaning = 'but (formal, in writing)' WHERE word = '但是';
UPDATE vocabulary SET meaning = 'but (casual, in speech)' WHERE word = '可是';
UPDATE vocabulary SET meaning = 'can (a skill you learned)' WHERE word = '会';
UPDATE vocabulary SET meaning = 'can (physically able right now)' WHERE word = '能';
UPDATE vocabulary SET meaning = 'can (allowed to; have permission)' WHERE word = '可以';
UPDATE vocabulary SET meaning = 'minute (in clock times)' WHERE word = '分';
UPDATE vocabulary SET meaning = 'minute (a length of time)' WHERE word = '分钟';
UPDATE vocabulary SET meaning = 'not enough; too little' WHERE word = '少';
UPDATE vocabulary SET meaning = 'a lot; plenty' WHERE word = '多';
UPDATE vocabulary SET meaning = 'how many? (expecting a small number)' WHERE word = '几';
UPDATE vocabulary SET meaning = 'how much? (expecting any number)' WHERE word = '多少';
UPDATE vocabulary SET meaning = 'quite a lot' WHERE word = '不少';
UPDATE vocabulary SET meaning = 'a little bit', pinyin = 'yìdiǎnr' WHERE word = '一点儿';
UPDATE vocabulary SET meaning = 'some (a handful of things)', pinyin = 'yìxiē' WHERE word = '一些';
UPDATE vocabulary SET meaning = 'unit of money (like saying "buck")' WHERE word = '块';
UPDATE vocabulary SET pinyin = 'yíxià' WHERE word = '一下';
UPDATE vocabulary SET pinyin = 'bú kèqi' WHERE word = '不客气';
UPDATE vocabulary SET meaning = 'ground, earth' WHERE word = '地' AND pinyin = 'dì';
UPDATE vocabulary SET meaning = 'turns a word into how an action is done' WHERE word = '地' AND pinyin = 'de';

-- 给 (verb, kept)
UPDATE vocabulary SET meaning = 'to give' WHERE id = 'b14db149-64c1-41a2-b09b-ae9658621692';

-- 后天 exact duplicate: 0 user_progress rows, 0 quiz_attempts. Nothing orphaned.
DELETE FROM vocabulary WHERE id = '1deb67ed-ce2c-47b8-ba30-d736ad1d21f6';

-- 给 (hsk1 ch16 preposition): the beginner verb sense (id b14db149…,
-- 12 attempts) is kept. Both rows are the same word 给 gěi, so the one
-- attempt on the preposition row is reassigned to the kept row rather
-- than left dangling — there is no FK on vocabulary, so a delete would
-- silently orphan it instead of erroring.
UPDATE quiz_attempts SET vocabulary_id = 'b14db149-64c1-41a2-b09b-ae9658621692'
  WHERE vocabulary_id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';
DELETE FROM user_progress WHERE vocabulary_id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';
DELETE FROM vocabulary WHERE id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';

-- 地 is NOT deduped: de (adverbial) and dì (ground) are different words
-- sharing a character, and both carry real attempts (4 and 11).
