#!/usr/bin/env python3
"""Apply the Aug 2026 vocabulary gloss/pinyin cleanup.

Single source of truth for the change set: rewrites
`src/data/hsk1_vocabulary.json` in place and emits the matching SQL for the
Supabase `vocabulary` table (which is what the app actually reads).

Run:  python3 content/vocab_fixes_20260828.py
"""
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
JSON_PATH = REPO / "src/data/hsk1_vocabulary.json"
SQL_PATH = REPO / "content/vocab_fixes_20260828.sql"

# (word, pinyin_match_or_None) -> {"meaning": ..., "pinyin": ...}
# pinyin_match disambiguates the two 地 readings; None means "the only row".
CHANGES: dict[tuple[str, str | None], dict[str, str]] = {
    # --- Answer leaks: gloss printed the answer in hanzi, or read as pinyin ---
    ("儿", "ér"): {"meaning": 'child; adds an "r" sound to the end of a word'},
    ("者", None): {"meaning": "a person who does something"},
    ("些", None): {"meaning": 'some (only after "one", "this" or "that")'},

    # --- Linguistics jargon the learner does not read ("MW", "suffix") ---
    ("两", None): {"meaning": "two (when counting things)"},
    ("二", None): {"meaning": "two (the number itself)"},
    ("个", None): {"meaning": "the all-purpose counting word"},
    ("本", None): {"meaning": "counting word for books"},
    ("口", None): {"meaning": "mouth; counting word for family members"},
    ("儿子", None): {"meaning": "son"},

    # --- Synonym pairs that shipped with identical glosses ---
    ("但是", None): {"meaning": "but (formal, in writing)"},
    ("可是", None): {"meaning": "but (casual, in speech)"},
    # 会/能/可以 is a three-way split, not a pair: 可以 was added via Chat on
    # 2026-09-07 as "can, may, be allowed to", which collided with 能.
    ("会", None): {"meaning": "can (a skill you learned)"},
    ("能", None): {"meaning": "can (physically able right now)"},
    ("可以", None): {"meaning": "can (allowed to; have permission)"},
    ("分", None): {"meaning": "minute (in clock times)"},
    ("分钟", None): {"meaning": "minute (a length of time)"},

    # --- Quantity cluster: 些/少 were a 50/50 coin flip in quiz history ---
    ("少", None): {"meaning": "not enough; too little"},
    ("多", None): {"meaning": "a lot; plenty"},
    ("几", None): {"meaning": "how many? (expecting a small number)"},
    ("多少", None): {"meaning": "how much? (expecting any number)"},
    ("不少", None): {"meaning": "quite a lot"},
    ("一点儿", None): {"meaning": "a little bit", "pinyin": "yìdiǎnr"},
    ("一些", None): {"meaning": "some (a handful of things)", "pinyin": "yìxiē"},

    # --- Wrong gloss: 块 is kuài; "yuan" is 元, a different character ---
    ("块", None): {"meaning": 'unit of money (like saying "buck")'},

    # --- Tone sandhi: 一 before 4th tone -> yí, otherwise yì; 不 before 4th -> bú ---
    ("一下", None): {"pinyin": "yíxià"},
    ("不客气", None): {"pinyin": "bú kèqi"},

    # --- 地 keeps both readings; only the jargon goes ---
    ("地", "dì"): {"meaning": "ground, earth"},
    ("地", "de"): {"meaning": "turns a word into how an action is done"},
}

# Both 给 rows share the pinyin "gěi", so word+pinyin would hit both and
# recreate the duplicate. Target by id. Not mirrored into the hsk1 JSON: the
# row kept here is the chat-source verb, which that file does not contain.
ID_CHANGES: list[tuple[str, str, dict[str, str]]] = [
    ("b14db149-64c1-41a2-b09b-ae9658621692", "给 (verb, kept)", {"meaning": "to give"}),
]


# Entries dropped from the JSON because their Supabase row is being deleted.
# (word, pinyin, part_of_speech) — 给 needs the PoS to pick the right one.
JSON_DELETIONS: set[tuple[str, str, str]] = {
    ("给", "gěi", "preposition"),
}


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    entries = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    before = len(entries)
    entries = [
        e
        for e in entries
        if (e["word"], e["pinyin"], e["part_of_speech"]) not in JSON_DELETIONS
    ]
    dropped = before - len(entries)

    json_hits = 0
    for entry in entries:
        for (word, pinyin), patch in CHANGES.items():
            if entry["word"] != word:
                continue
            if pinyin is not None and entry["pinyin"] != pinyin:
                continue
            entry.update(patch)
            json_hits += 1

    JSON_PATH.write_text(
        json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    lines = [
        "-- Vocabulary gloss/pinyin cleanup, 2026-08-28",
        "-- Generated by content/vocab_fixes_20260828.py",
        "-- Backup taken first: backups/vocabulary_backup_20260828_114759.json",
        "",
    ]
    for (word, pinyin), patch in CHANGES.items():
        sets = ", ".join(f"{col} = {sql_str(val)}" for col, val in sorted(patch.items()))
        where = f"word = {sql_str(word)}"
        if pinyin is not None:
            where += f" AND pinyin = {sql_str(pinyin)}"
        lines.append(f"UPDATE vocabulary SET {sets} WHERE {where};")

    lines.append("")
    for row_id, label, patch in ID_CHANGES:
        sets = ", ".join(f"{col} = {sql_str(val)}" for col, val in sorted(patch.items()))
        lines.append(f"-- {label}")
        lines.append(f"UPDATE vocabulary SET {sets} WHERE id = '{row_id}';")

    # Deletes are listed with their measured blast radius. There are no foreign
    # keys on `vocabulary`, so nothing cascades — but user_progress and
    # quiz_attempts rows pointing at a deleted id are left dangling, and a
    # dangling user_progress row silently drops the word from the user's list.
    lines += [
        "",
        "-- 后天 exact duplicate: 0 user_progress rows, 0 quiz_attempts. Nothing orphaned.",
        "DELETE FROM vocabulary WHERE id = '1deb67ed-ce2c-47b8-ba30-d736ad1d21f6';",
        "",
        "-- 给 (hsk1 ch16 preposition): the beginner verb sense (id b14db149…,",
        "-- 12 attempts) is kept. Both rows are the same word 给 gěi, so the one",
        "-- attempt on the preposition row is reassigned to the kept row rather",
        "-- than left dangling — there is no FK on vocabulary, so a delete would",
        "-- silently orphan it instead of erroring.",
        "UPDATE quiz_attempts SET vocabulary_id = 'b14db149-64c1-41a2-b09b-ae9658621692'",
        "  WHERE vocabulary_id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';",
        "DELETE FROM user_progress WHERE vocabulary_id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';",
        "DELETE FROM vocabulary WHERE id = 'bea9cde9-1873-4a95-b3ed-1480fff2a29f';",
        "",
        "-- 地 is NOT deduped: de (adverbial) and dì (ground) are different words",
        "-- sharing a character, and both carry real attempts (4 and 11).",
    ]

    SQL_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"patched {json_hits} JSON entries, dropped {dropped}; "
        f"wrote {SQL_PATH.relative_to(REPO)}"
    )


if __name__ == "__main__":
    main()
